# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: partbook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='partbook.proto',
  package='tutorial',
  serialized_pb=_b('\n\x0epartbook.proto\x12\x08tutorial\"4\n\x04Part\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06partid\x18\x02 \x02(\x05\x12\x0e\n\x06vendor\x18\x03 \x01(\t\"+\n\x0bPartDetails\x12\x1c\n\x04part\x18\x01 \x03(\x0b\x32\x0e.tutorial.Part')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PART = _descriptor.Descriptor(
  name='Part',
  full_name='tutorial.Part',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.Part.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partid', full_name='tutorial.Part.partid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vendor', full_name='tutorial.Part.vendor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=80,
)


_PARTDETAILS = _descriptor.Descriptor(
  name='PartDetails',
  full_name='tutorial.PartDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='part', full_name='tutorial.PartDetails.part', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=125,
)

_PARTDETAILS.fields_by_name['part'].message_type = _PART
DESCRIPTOR.message_types_by_name['Part'] = _PART
DESCRIPTOR.message_types_by_name['PartDetails'] = _PARTDETAILS

Part = _reflection.GeneratedProtocolMessageType('Part', (_message.Message,), dict(
  DESCRIPTOR = _PART,
  __module__ = 'partbook_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Part)
  ))
_sym_db.RegisterMessage(Part)

PartDetails = _reflection.GeneratedProtocolMessageType('PartDetails', (_message.Message,), dict(
  DESCRIPTOR = _PARTDETAILS,
  __module__ = 'partbook_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.PartDetails)
  ))
_sym_db.RegisterMessage(PartDetails)


# @@protoc_insertion_point(module_scope)
